
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijrshaxmapzehkrvcsyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqcnNoYXhtYXB6ZWhrcnZjc3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTgzNjA0NjUsImV4cCI6MjAxMzkzNjQ2NX0.ZSl6R5A8TgCdRmH-GCd52qNhzHilxvU4-_7TCQ_I_oM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
