// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuzhnqelsfexsjgosflv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1emhucWVsc2ZleHNqZ29zZmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODM5MDUsImV4cCI6MjA2MTA1OTkwNX0.xDxGXa3ykyWxgORE9j8vtQp6AElgqyLeFofzaVJdx-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);